-- Word lists and geography used by the synthetic data generator.
-- Everything lives in the private `seed` schema and is dropped at the end.
--
-- Synthetic-data safety rules:
--   * SSNs use the 9xx area (never issued as SSNs) with group 00–49 (outside ITIN ranges).
--   * Emails use the reserved example.com / example.net / example.org domains.
--   * Phone numbers use the 555 exchange.

create schema if not exists seed;
revoke all on schema seed from public, anon, authenticated;

drop table if exists seed.lists;
create unlogged table seed.lists (name text primary key, items text[] not null);

insert into seed.lists values
('male', array['James','Michael','Robert','John','David','William','Richard','Joseph','Thomas','Christopher','Charles','Daniel','Matthew','Anthony','Mark','Donald','Steven','Andrew','Paul','Joshua','Kenneth','Kevin','Brian','Timothy','Ronald','George','Jason','Edward','Jeffrey','Ryan','Jacob','Nicholas','Gary','Eric','Jonathan','Stephen','Larry','Justin','Scott','Brandon','Benjamin','Samuel','Gregory','Alexander','Patrick','Frank','Raymond','Jack','Dennis','Jerry','Tyler','Aaron','Jose','Adam','Nathan','Henry','Zachary','Douglas','Peter','Kyle','Noah','Ethan','Jeremy','Christian','Walter','Keith','Austin','Roger','Terry','Sean','Gerald','Carl','Dylan','Harold','Jordan','Jesse','Bryan','Lawrence','Arthur','Gabriel','Bruce','Logan','Albert','Willie','Alan','Eugene','Russell','Elijah','Randy','Wayne','Juan','Carlos','Luis','Miguel','Jorge','Marcus','Darnell','Terrence','Andre','Jamal','DeShawn','Malik','Tyrone','Reginald','Cedric','Omar','Tariq','Yusuf','Ahmed','Hassan','Khalid','Ibrahim','Mohammed','Wei','Jun','Hao','Minh','Tuan','Hyun','Jin','Raj','Arjun','Vikram','Sanjay','Rahul','Kwame','Chidi','Emeka','Obinna','Tunde','Mateo','Diego','Santiago','Alejandro','Rafael','Desmond','Winston','Leon','Isaiah','Xavier','Dominic','Vincent','Theodore','Calvin','Franklin']),
('female', array['Mary','Patricia','Jennifer','Linda','Elizabeth','Barbara','Susan','Jessica','Sarah','Karen','Lisa','Nancy','Betty','Margaret','Sandra','Ashley','Kimberly','Emily','Donna','Michelle','Carol','Amanda','Dorothy','Melissa','Deborah','Stephanie','Rebecca','Sharon','Laura','Cynthia','Kathleen','Amy','Angela','Shirley','Anna','Brenda','Pamela','Emma','Nicole','Helen','Samantha','Katherine','Christine','Debra','Rachel','Carolyn','Janet','Catherine','Maria','Heather','Diane','Ruth','Julie','Olivia','Joyce','Virginia','Victoria','Kelly','Lauren','Christina','Joan','Evelyn','Judith','Megan','Andrea','Cheryl','Hannah','Jacqueline','Martha','Gloria','Teresa','Ann','Sara','Madison','Frances','Kathryn','Janice','Jean','Abigail','Alice','Julia','Judy','Sophia','Grace','Denise','Amber','Doris','Marilyn','Danielle','Beverly','Isabella','Theresa','Diana','Natalie','Brittany','Charlotte','Marie','Kayla','Alexis','Lori','Keisha','Latoya','Tamika','Ebony','Aaliyah','Jasmine','Imani','Nia','Fatima','Aisha','Layla','Noor','Mariam','Yasmin','Mei','Lin','Hui','Thuy','Linh','Priya','Ananya','Deepa','Kavya','Adaeze','Ngozi','Chioma','Amara','Folake','Sofia','Valentina','Camila','Lucia','Gabriela','Ximena','Rosa','Carmen','Yvonne','Gwendolyn','Loretta','Monique','Tanisha','Renee','Colleen','Bridget']),
('last', array['Smith','Johnson','Williams','Brown','Jones','Garcia','Miller','Davis','Rodriguez','Martinez','Hernandez','Lopez','Gonzalez','Wilson','Anderson','Thomas','Taylor','Moore','Jackson','Martin','Lee','Perez','Thompson','White','Harris','Sanchez','Clark','Ramirez','Lewis','Robinson','Walker','Young','Allen','King','Wright','Scott','Torres','Nguyen','Hill','Flores','Green','Adams','Nelson','Baker','Hall','Rivera','Campbell','Mitchell','Carter','Roberts','Gomez','Phillips','Evans','Turner','Diaz','Parker','Cruz','Edwards','Collins','Reyes','Stewart','Morris','Morales','Murphy','Cook','Rogers','Gutierrez','Ortiz','Morgan','Cooper','Peterson','Bailey','Reed','Kelly','Howard','Ramos','Kim','Cox','Ward','Richardson','Watson','Brooks','Chavez','Wood','James','Bennett','Gray','Mendoza','Ruiz','Hughes','Price','Alvarez','Castillo','Sanders','Patel','Myers','Long','Ross','Foster','Jimenez','Powell','Jenkins','Perry','Russell','Sullivan','Bell','Coleman','Butler','Henderson','Barnes','Fisher','Vasquez','Simmons','Romero','Jordan','Patterson','Alexander','Hamilton','Graham','Reynolds','Griffin','Wallace','Moreno','West','Cole','Hayes','Bryant','Herrera','Gibson','Ellis','Tran','Medina','Aguilar','Stevens','Murray','Ford','Castro','Marshall','Owens','Harrison','Fernandez','McDonald','Woods','Washington','Kennedy','Wells','Vargas','Henry','Chen','Freeman','Webb','Tucker','Guzman','Burns','Crawford','Olson','Simpson','Porter','Hunter','Gordon','Mendez','Silva','Shaw','Snyder','Mason','Dixon','Munoz','Hunt','Hicks','Holmes','Palmer','Wagner','Black','Robertson','Boyd','Rose','Stone','Salazar','Fox','Warren','Mills','Meyer','Rice','Schmidt','Garza','Daniels','Ferguson','Nichols','Stephens','Soto','Weaver','Ryan','Gardner','Payne','Grant','Dunn','Spencer','Hawkins','Arnold','Pierce','Hansen','Peters','Santos','Hart','Bradley','Knight','Elliott','Cunningham','Duncan','Armstrong','Hudson','Carroll','Lane','Riley','Andrews','Ray','Delgado','Berry','Perkins','Hoffman','Johnston','Matthews','Pena','Richards','Willis','Carpenter','Lawrence','Okafor','Adeyemi','Okeke','Nwosu','Mensah','Owusu','Boateng','Haddad','Khalil','Nasser','Rahman','Hussain','Ali','Khan','Siddiqui','Park','Choi','Kang','Cho','Yoon','Wang','Zhang','Liu','Huang','Zhao','Pham','Le','Hoang','Vu','Shah','Mehta','Rao','Iyer','Desai','Gupta','O''Brien','O''Connor','Byrne','Kowalski','Novak','Schneider','Muller','Rossi','Russo','Esposito','Greco','Dubois','Levy','Cohen','Goldberg','Friedman','Bishop','Chambers','Holland','Lucas','Watts','Wheeler','Fleming','Sutton','Barber','Bowman','Fuller','Harper','Mack','Tate','Quinn','Frazier','Banks','Glover','Pope','Dawson','Rowe','Joyner','Whitaker','Pittman','Hairston','Blackwell','Gaines','Battle']),
('streets', array['N Charles St','St Paul St','Greenmount Ave','York Rd','Harford Rd','Belair Rd','Eastern Ave','Liberty Heights Ave','Reisterstown Rd','Park Heights Ave','Northern Pkwy','Cold Spring Ln','Falls Rd','Roland Ave','Edmondson Ave','Frederick Rd','Wilkens Ave','Washington Blvd','Ritchie Hwy','Crain Hwy','Dorsey Rd','Snowden River Pkwy','Columbia Pike','Georgia Ave','Colesville Rd','University Blvd','New Hampshire Ave','Wisconsin Ave','Connecticut Ave','Rockville Pike','Veirs Mill Rd','Randolph Rd','Annapolis Rd','Forest Dr','Bay Ridge Ave','Joppa Rd','Loch Raven Blvd','Dulaney Valley Rd','Perring Pkwy','Hillen Rd','Old Court Rd','Liberty Rd','Security Blvd','Rolling Rd','Ingleside Ave','Maple Ave','Oak St','Elm St','Cedar Ln','Park Ave','Chestnut Ave','Linden Ave','Madison St','Monroe St','Jefferson St','Lombard St','Fayette St','Fleet St','Boston St','Clinton St','Light St','Fort Ave','Hanover St','Wilson Blvd','Glebe Rd','Fairfax Dr','14th St NW','16th St NW','U St NW','H St NE','Benning Rd NE','Rhode Island Ave NE','Seminary Rd','Duke St','King St','Main St','Church St','Mill Rd','Spring Ave','Highland Ave','Magnolia Dr','Willow Way','Hickory Ln','Laurel Ct','Brookside Dr']),
('employers', array['Johns Hopkins Hospital','University of Maryland Medical System','Social Security Administration','Northrop Grumman','T. Rowe Price','Under Armour','Constellation Energy','Baltimore City Public Schools','U.S. Census Bureau','National Institutes of Health','Lockheed Martin','Marriott International','CareFirst BlueCross BlueShield','McCormick & Company','BGE','Amazon','MedStar Health','Montgomery County Public Schools','Anne Arundel County Government','Howard County General Hospital','Booz Allen Hamilton','Leidos','Fort Meade (DoD)','U.S. Naval Academy','Maryland Transit Administration','Washington Metropolitan Area Transit Authority','Discovery Inc.','Capital One','Fannie Mae','Deloitte','Giant Food','Safeway','Home Depot','Target','Walmart','Royal Farms','Whiting-Turner Contracting','Clark Construction','Kaiser Permanente','Inova Health System','Arlington Public Schools','Fairfax County Government','Georgetown University','University of Maryland','Towson University','Morgan State University','Self-employed','Uber','U.S. Postal Service','Maryland State Police','Baltimore County Government','Wegmans','Stanley Black & Decker','Exelon','Allegis Group','Legg Mason','Johns Hopkins University','Kennedy Krieger Institute','Mercy Medical Center','Sinclair Broadcast Group']),
('occupations', array['Registered Nurse','Teacher','Software Engineer','Accountant','Administrative Assistant','Customer Service Representative','Sales Associate','Project Manager','Electrician','Mechanic','Police Officer','Firefighter','Physician','Pharmacist','Paralegal','Attorney','Analyst','Engineer','Bus Operator','Truck Driver','Chef','Server','Cashier','Warehouse Associate','Carpenter','Plumber','HVAC Technician','Social Worker','Professor','Research Scientist','Dental Hygienist','Medical Assistant','Physical Therapist','IT Specialist','Security Officer','Real Estate Agent','Insurance Agent','Financial Advisor','Contractor','Graphic Designer','Marketing Manager','Human Resources Specialist','Operations Manager','Program Analyst','Postal Carrier','Barber','Cosmetologist','Pilot','Flight Attendant','Veterinary Technician','Librarian','Military Service Member','Federal Employee','Nurse Practitioner','Data Scientist','Consultant','Store Manager','Construction Laborer','Home Health Aide','Clergy']),
('merchants', array['GIANT FOOD #0123 BALTIMORE MD','SAFEWAY #1456 SILVER SPRING MD','WEGMANS #085 COLUMBIA MD','SHELL OIL 57442 TOWSON MD','EXXONMOBIL 4471 GLEN BURNIE MD','ROYAL FARMS #203 BALTIMORE MD','CVS/PHARMACY #01723','AMAZON.COM*2K4P1 AMZN.COM/BILL','TARGET 00012345 COLUMBIA MD','STARBUCKS #11532 BALTIMORE MD','CHIPOTLE 1893 TOWSON MD','UBER *TRIP HELP.UBER.COM','NETFLIX.COM LOS GATOS CA','SPOTIFY USA NEW YORK NY','THE HOME DEPOT #2503','LOWES #00614 GLEN BURNIE MD','COSTCO WHSE #0213 COLUMBIA MD','TRADER JOE S #647 TOWSON MD','DUNKIN #332917 ANNAPOLIS MD','MCDONALD''S F12345 BALTIMORE MD','WAWA 8123 ARLINGTON VA','HARRIS TEETER #0310 WASHINGTON DC','ALDI 70041 BALTIMORE MD','WALGREENS #7732 SILVER SPRING MD','PANERA BREAD #601 COLUMBIA MD','APPLE.COM/BILL CUPERTINO CA','LYFT *RIDE SAN FRANCISCO CA','DOORDASH*DASHPASS','PETSMART #1142 TOWSON MD','BEST BUY 00018 COLUMBIA MD','KOHL''S #0655 GLEN BURNIE MD','SUNOCO 0812 ANNAPOLIS MD','PARKMOBILE BALTIMORE MD','MTA CHARM CARD BALTIMORE MD','WMATA SMARTRIP WASHINGTON DC']),
('billers', array['BGE ELECTRIC PAYMENT','VERIZON WIRELESS PAYMENT','COMCAST XFINITY PAYMENT','GEICO AUTO INSURANCE','STATE FARM INSURANCE','PEPCO ELECTRIC PAYMENT','WASHINGTON GAS PAYMENT','T-MOBILE PAYMENT','BALTIMORE CITY WATER','PLANET FITNESS DUES','PROGRESSIVE INS PREM','DOMINION ENERGY VA','LIBERTY MUTUAL INS','ANNE ARUNDEL CO WATER','ATT*BILL PAYMENT']),
('bene_relationships', array['Spouse','Child','Parent','Sibling','Grandchild','Niece/Nephew','Friend','Domestic partner']),
('former_staff', array['Deborah Klein','Harold Jenkins','Patricia Owens','Gregory Sims','Lorraine Duckett','Michael Petrakis','Yvette Carrington','Stanley Brooks','Monica Alvarez','Raymond Tully']);

drop table if exists seed.geo;
create unlogged table seed.geo (
  idx serial primary key, city text not null, state char(2) not null, zip text not null,
  branch_id smallint, area_codes text[] not null
);
insert into seed.geo (city, state, zip, branch_id, area_codes) values
 ('Baltimore','MD','21201',1,'{410,443,667}'),('Baltimore','MD','21202',1,'{410,443,667}'),('Baltimore','MD','21205',1,'{410,443}'),
 ('Baltimore','MD','21206',1,'{410,443}'),('Baltimore','MD','21209',1,'{410,443}'),('Baltimore','MD','21210',1,'{410,443}'),
 ('Baltimore','MD','21211',1,'{410,443}'),('Baltimore','MD','21212',1,'{410,443}'),('Baltimore','MD','21213',1,'{410,443}'),
 ('Baltimore','MD','21214',1,'{410,443}'),('Baltimore','MD','21215',1,'{410,443}'),('Baltimore','MD','21216',1,'{410,443}'),
 ('Baltimore','MD','21217',1,'{410,443}'),('Baltimore','MD','21218',1,'{410,443}'),('Baltimore','MD','21224',1,'{410,443}'),
 ('Baltimore','MD','21229',1,'{410,443}'),('Baltimore','MD','21230',1,'{410,443}'),('Baltimore','MD','21231',1,'{410,443}'),
 ('Baltimore','MD','21239',1,'{410,443}'),
 ('Towson','MD','21204',2,'{410,443}'),('Towson','MD','21286',2,'{410,443}'),('Parkville','MD','21234',2,'{410,443}'),
 ('Timonium','MD','21093',2,'{410,443}'),('Cockeysville','MD','21030',2,'{410,443}'),('Perry Hall','MD','21128',2,'{410,443}'),
 ('Rosedale','MD','21237',2,'{410,443}'),('Essex','MD','21221',2,'{410,443}'),
 ('Columbia','MD','21044',3,'{410,443}'),('Columbia','MD','21045',3,'{410,443}'),('Columbia','MD','21046',3,'{410,443}'),
 ('Ellicott City','MD','21042',3,'{410,443}'),('Ellicott City','MD','21043',3,'{410,443}'),('Laurel','MD','20707',3,'{301,240}'),
 ('Catonsville','MD','21228',3,'{410,443}'),('Elkridge','MD','21075',3,'{410,443}'),('Frederick','MD','21701',3,'{301,240}'),
 ('Annapolis','MD','21401',4,'{410,443}'),('Annapolis','MD','21403',4,'{410,443}'),('Arnold','MD','21012',4,'{410,443}'),
 ('Severna Park','MD','21146',4,'{410,443}'),('Edgewater','MD','21037',4,'{410,443}'),('Crofton','MD','21114',4,'{410,301}'),
 ('Silver Spring','MD','20901',5,'{301,240}'),('Silver Spring','MD','20902',5,'{301,240}'),('Silver Spring','MD','20904',5,'{301,240}'),
 ('Silver Spring','MD','20910',5,'{301,240}'),('Takoma Park','MD','20912',5,'{301,240}'),('Rockville','MD','20850',5,'{301,240}'),
 ('Rockville','MD','20852',5,'{301,240}'),('Bethesda','MD','20814',5,'{301,240}'),('Gaithersburg','MD','20878',5,'{301,240}'),
 ('Hyattsville','MD','20782',5,'{301,240}'),('College Park','MD','20740',5,'{301,240}'),
 ('Washington','DC','20001',6,'{202}'),('Washington','DC','20002',6,'{202}'),('Washington','DC','20003',6,'{202}'),
 ('Washington','DC','20009',6,'{202}'),('Washington','DC','20010',6,'{202}'),('Washington','DC','20011',6,'{202}'),
 ('Washington','DC','20016',6,'{202}'),('Washington','DC','20019',6,'{202}'),('Washington','DC','20036',6,'{202}'),
 ('Arlington','VA','22201',7,'{703,571}'),('Arlington','VA','22203',7,'{703,571}'),('Arlington','VA','22204',7,'{703,571}'),
 ('Alexandria','VA','22301',7,'{703,571}'),('Alexandria','VA','22314',7,'{703,571}'),('Falls Church','VA','22046',7,'{703,571}'),
 ('Fairfax','VA','22030',7,'{703,571}'),('McLean','VA','22101',7,'{703,571}'),
 ('Glen Burnie','MD','21061',8,'{410,443}'),('Glen Burnie','MD','21060',8,'{410,443}'),('Pasadena','MD','21122',8,'{410,443}'),
 ('Severn','MD','21144',8,'{410,443}'),('Linthicum Heights','MD','21090',8,'{410,443}'),('Brooklyn Park','MD','21225',8,'{410,443}'),
 ('Odenton','MD','21113',8,'{410,301}'),
 ('Richmond','VA','23220',null,'{804}'),('Philadelphia','PA','19103',null,'{215,267}'),('Wilmington','DE','19801',null,'{302}'),
 ('York','PA','17401',null,'{717}'),('Charlotte','NC','28202',null,'{704,980}'),('Raleigh','NC','27601',null,'{919}'),
 ('Atlanta','GA','30309',null,'{404,678}'),('Norfolk','VA','23510',null,'{757}'),('Salisbury','MD','21801',4,'{410,443}'),
 ('Hagerstown','MD','21740',3,'{301,240}');
