/**
 * Typed contracts shared by discovery, replay, and the calling agent.
 *
 * A Capability is the reviewable, versioned artifact produced by one successful
 * discovery run. It is deliberately decoupled from the model transcript: it holds
 * only what replay needs (steps, targets, checkpoints, conditions) and what a
 * caller needs (inputs, outputs, result contract).
 */
import { z } from "zod";

// ---------------------------------------------------------------------------
// Locators: how a control is identified. All strategies are based on what a
// person perceives (role + accessible name, label, visible text, table
// row/column, link destinations). None depend on CSS classes or test IDs.
// Reading order is used only when a locator explicitly requests the first link.
// ---------------------------------------------------------------------------

const Scope = z.object({ role: z.string(), name: z.string().optional() }).strict();

export const Locator = z.discriminatedUnion("by", [
  // A destination family visible in the accessibility tree. "first" is an explicit
  // task requirement, never an implicit fallback for an ambiguous target.
  z.object({ by: z.literal("link"), hrefPrefix: z.string().min(1), position: z.literal("first").optional(), within: Scope.optional() }).strict(),
  // Without a name: "the single <role> in <within>", e.g. the one member link in a results table.
  // It must still match exactly one element, so it never picks among several.
  // namePattern (a regex over the accessible name) is only generated by the recorder, e.g. to
  // accept any count in a tab such as "Accounts 3" / "Accounts 11".
  z
    .object({ by: z.literal("role"), role: z.string(), name: z.string().optional(), namePattern: z.string().optional(), exact: z.boolean().optional(), within: Scope.optional() })
    .strict(),
  z.object({ by: z.literal("label"), label: z.string(), within: Scope.optional() }).strict(),
  z.object({ by: z.literal("text"), text: z.string(), within: Scope.optional() }).strict(),
  // The value displayed right after a caption ("Current balance  $1,234.56"): label/value
  // pairs in non-semantic markup, definition lists, vertical key/value tables.
  z.object({ by: z.literal("field"), field: z.string(), within: Scope.optional() }).strict(),
  // A table cell addressed like a person reads it: "the row named X, the column headed Y".
  z.object({ by: z.literal("cell"), row: z.string(), column: z.string(), within: Scope.optional() }).strict(),
]);
export type Locator = z.infer<typeof Locator>;

/** Ordered strategies: the first is primary, the rest are fallbacks verified at record time. */
export const Target = z
  .object({
    description: z.string(),
    locators: z.array(Locator).min(1),
  })
  .strict();
export type Target = z.infer<typeof Target>;

// ---------------------------------------------------------------------------
// Checkpoints: asserted after a step and at the end, instead of assuming a click worked.
// ---------------------------------------------------------------------------

export const Checkpoint = z.discriminatedUnion("kind", [
  /** Path (+query) of the page, with {{input}} placeholders. Exact match. */
  z.object({ kind: z.literal("url"), pattern: z.string() }).strict(),
  z.object({ kind: z.literal("visible"), target: Target }).strict(),
]);
export type Checkpoint = z.infer<typeof Checkpoint>;

// ---------------------------------------------------------------------------
// Steps
// ---------------------------------------------------------------------------

export const ActionType = z.enum(["click", "fill", "select", "press", "extract"]);
export type ActionType = z.infer<typeof ActionType>;

export const OutputType = z.enum(["money", "number", "text"]);
export type OutputType = z.infer<typeof OutputType>;
export const ExtractionSource = z.enum(["text", "href"]);
export type ExtractionSource = z.infer<typeof ExtractionSource>;

export const Step = z
  .object({
    id: z.string(),
    intent: z.string(),
    action: ActionType,
    target: Target,
    /** Literal, "{{input}}" or "{{secret.name}}". Secrets are only ever references. */
    value: z.string().optional(),
    /** For extract: which declared output receives the value. */
    output: z.string().optional(),
    /** Text by default; href reads and resolves a link's destination URL. */
    extract: ExtractionSource.optional(),
    expect: z.array(Checkpoint).default([]),
    timeoutMs: z.number().int().positive().default(15_000),
  })
  .strict();
export type Step = z.infer<typeof Step>;

// ---------------------------------------------------------------------------
// Conditions: runtime states replay must recognise and respond to deliberately.
// They come from the app profile (shared by every capability on that vendor app).
// ---------------------------------------------------------------------------

export const ConditionKind = z.enum([
  "business", // a legitimate answer the caller needs ("no such member")
  "recoverable", // known interstitial / transient error with a bounded fix
  "escalate", // needs human judgement; pause and hand the live session over
  "fatal", // stop now with a debuggable error
]);
export type ConditionKind = z.infer<typeof ConditionKind>;

export const Condition = z
  .object({
    id: z.string(),
    kind: ConditionKind,
    /** Present when this element is visible. */
    when: Locator,
    message: z.string(),
    /** For recoverable conditions: clicks that clear it. */
    recover: z.array(Locator).optional(),
    maxRecoveries: z.number().int().min(0).default(2),
  })
  .strict();
export type Condition = z.infer<typeof Condition>;

// ---------------------------------------------------------------------------
// Capability (the artifact)
// ---------------------------------------------------------------------------

export const InputSpec = z
  .object({
    name: z.string().regex(/^[a-z][a-z0-9_]*$/),
    type: z.literal("string"),
    description: z.string(),
    pattern: z.string().optional(),
  })
  .strict();

export const OutputSpec = z
  .object({
    name: z.string().regex(/^[a-z][a-z0-9_]*$/),
    type: OutputType,
    description: z.string(),
    currency: z.string().optional(),
  })
  .strict();

export const Capability = z
  .object({
    schemaVersion: z.literal("1.0"),
    id: z.string().regex(/^[a-z0-9]+(?:[.-][a-z0-9]+)*$/),
    version: z.number().int().positive(),
    name: z.string(),
    description: z.string(),
    app: z
      .object({
        id: z.string(),
        surface: z.literal("web"),
        /** Where discovery ran. Replay may target another allow-listed origin (another tenant). */
        recordedOrigin: z.string().url(),
        entryPath: z.string(),
      })
      .strict(),
    inputs: z.array(InputSpec),
    secrets: z.array(z.string()),
    outputs: z.array(OutputSpec),
    steps: z.array(Step).min(1),
    success: z.array(Checkpoint),
    conditions: z.array(Condition),
    /** How a caller runs it; generated at compile time. */
    usage: z.object({ replay: z.string() }).strict().optional(),
    provenance: z
      .object({
        discoveredAt: z.string(),
        runId: z.string(),
        goal: z.string(),
        model: z.string(),
        llmCalls: z.number().int(),
      })
      .strict(),
  })
  .strict();
export type Capability = z.infer<typeof Capability>;

// ---------------------------------------------------------------------------
// Replay result contract
// ---------------------------------------------------------------------------

export type RunStatus = "success" | "business_outcome" | "needs_human" | "failed";

export interface InterventionRequest {
  id: string;
  capability: string;
  stepId: string | null;
  stepIntent: string | null;
  reason: string;
  url: string;
  screenshot: string | null;
  snapshot: string | null;
  requestedAt: string;
}

export interface RunResult {
  runId: string;
  capability: string;
  status: RunStatus;
  outputs?: Record<string, string | number>;
  outcome?: { id: string; message: string };
  error?: {
    code: string;
    stepId: string | null;
    expected: string;
    observed: string;
    url: string;
    screenshot?: string;
    snapshot?: string;
  };
  intervention?: InterventionRequest;
  recoveries: { stepId: string; condition: string }[];
  handoffs: { requestId: string; reason: string; humanActions: number; resumedBy: string }[];
  durationMs: number;
}
